version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pico_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: pico
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: piezo_data
    ports:
      - "5432:5432" 
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: 