[package]
name = "pico_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
egui_plot = "0.29"
serialport = "4.2"
chrono = "0.4"
crossbeam-channel = "0.5"
ringbuffer = "0.15"
realfft = "3.3" 